import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { cleanExtractedText, detectFormat, extractDocumentText } from "@/lib/documentText";
import { appearsIn } from "@/lib/validation";
import { DEMO_RESUME } from "@/lib/demoData";

// Fixtures are the fictional demo resume, generated by tests/fixtures/generate.mjs.
const fixture = (name: string) => new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));

// Resume lines the evidence stage would typically quote.
const SAMPLE_LINES = [
  "Built and maintained React and TypeScript dashboards used by the operations team to track shipments.",
  "Reduced dashboard load time by 40% by introducing pagination and query indexing.",
  "B.S. in Computer Science — Cascade Valley University (fictional), 2020",
  // Wraps across two lines in the PDF; verification must still match it.
  "Comfortable across the stack, with a focus on React front-ends and Node.js services.",
];

describe("extractDocumentText", () => {
  it.each([
    ["demo-resume.pdf", "pdf"],
    ["demo-resume.docx", "docx"],
  ] as const)("extracts %s so resume lines survive quote verification", async (name, format) => {
    const result = await extractDocumentText(fixture(name), name);
    expect(result.format).toBe(format);
    if (format === "pdf") expect(result.pages).toBe(1);
    // Integration point: the evidence stage's quotes are verified against this text.
    for (const line of SAMPLE_LINES) expect(appearsIn(result.text, line)).toBe(true);
    // Line structure is preserved (bullets stay on separate lines).
    expect(result.text.split("\n").length).toBeGreaterThan(20);
    expect(result.text.length).toBeGreaterThan(DEMO_RESUME.length * 0.9);
  });

  it("rejects empty and oversized files", async () => {
    await expect(extractDocumentText(new Uint8Array(), "a.pdf")).rejects.toMatchObject({ code: "empty_file" });
    await expect(extractDocumentText(new Uint8Array(5 * 1024 * 1024), "a.pdf")).rejects.toMatchObject({ code: "file_too_large" });
  });

  it("gives a clear error for a corrupt PDF", async () => {
    const corrupt = new TextEncoder().encode("%PDF-1.4\nthis is not really a pdf");
    await expect(extractDocumentText(corrupt, "broken.pdf")).rejects.toMatchObject({ code: "unreadable_file" });
  });
});

describe("detectFormat", () => {
  it("uses file contents, not the file name", () => {
    expect(detectFormat(fixture("demo-resume.pdf"), "renamed.docx")).toBe("pdf");
    expect(() => detectFormat(new TextEncoder().encode("plain text"), "resume.pdf")).toThrow(/PDF or Word/);
  });

  it("explains that legacy .doc files are unsupported", () => {
    expect(() => detectFormat(new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0, 0]), "old.doc")).toThrow(/\.doc/);
  });
});

describe("cleanExtractedText", () => {
  it("normalises whitespace without merging lines", () => {
    expect(cleanExtractedText("  Name \r\n\r\n\r\n\r\n- Built  things here \n")).toBe("Name\n\n- Built things here");
  });
});
